version: '3'

services:
  
  rabbitmq:
    container_name: microservices-rabbitmq
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      
#  advertise: 
#    container_name: advertise
#    environment: 
#      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
#      - MONGODB_ADVERTISE_PASSWORD=$MONGODB_ADVERTISE_PASSWORD
#    image: ivanp81/advertise
#    depends_on: 
#      - advertise-mongodb
#       
#  advertise-mongodb:
#    container_name: advertise-mongodb
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_ROOT_USERNAME
#      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD
#      - MONGODB_ADVERTISE_PASSWORD=$MONGODB_ADVERTISE_PASSWORD
#    image: ivanp81/advertise-mongodb
#    command: mongod --smallfiles
    
  advertise-search: 
    container_name: advertise-search
    environment: 
      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
    image: ivanp81/advertise-search
    depends_on: 
      - advertise-search-elasticsearch
  
  advertise-search-elasticsearch:
    container_name: advertise-search-elasticsearch
    image: elasticsearch:2.4
  