version: '3'

services:
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
               
  advertise-mongodb:
    image: mongo:3.0 
    ports:
      - 27017:27017

  advertise-index-elasticsearch: 
    image: elasticsearch:2.4
    ports:
      - 9200:9200
      - 9300:9300