version: '3'

services:
  
  advertise-ui:
     container_name: advertise-ui
     image: ivanp81/advertise-ui
     restart: unless-stopped
     depends_on:
       - advertise-gateway
     ports:
       - 80:80
       
  advertise-gateway:
     container_name: advertise-gateway
     image: ivanp81/advertise-gateway
     restart: always
     depends_on:
       - advertise
       - advertise-search
     ports:
       - 8080:8080
  
  advertise-rabbitmq:
    container_name: advertise-rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped #always
    ports:
      - 15672:15672
      
  advertise: 
    container_name: advertise
    environment:
      - VIRTUAL_HOST=advertise.local 
      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
      - MONGODB_ADVERTISE_PASSWORD=$MONGODB_ADVERTISE_PASSWORD
      - RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD
    image: ivanp81/advertise
    restart: unless-stopped #always
    depends_on: 
      - advertise-mongodb
      - advertise-rabbitmq
       
  advertise-mongodb:
    container_name: advertise-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD
      - MONGODB_ADVERTISE_PASSWORD=$MONGODB_ADVERTISE_PASSWORD
    image: ivanp81/advertise-mongodb
    restart: unless-stopped #always
    command: mongod --smallfiles
    
  advertise-search: 
    container_name: advertise-search
    environment: 
      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
      - RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD
    image: ivanp81/advertise-search
    restart: unless-stopped #always
    depends_on: 
      - advertise-search-elasticsearch
      - advertise-rabbitmq
  
  advertise-search-elasticsearch:
    container_name: advertise-search-elasticsearch
    image: elasticsearch:2.4
    restart: unless-stopped #always