export const GET_ADVERTISES_RESPONSE = 'GET_ADVERTISES_RESPONSE';
export const GET_ADVERTISE_RESPONSE = 'GET_ADVERTISE_RESPONSE';
export const ADD_NEW_ADVERTISE_RESPONSE = 'ADD_NEW_ADVERTISE_RESPONSE';
export const UPDATE_EXISTING_ADVERTISE_RESPONSE = 'UPDATE_EXISTING_ADVERTISE_RESPONSE';
export const DELETE_ADVERTISE_RESPONSE = 'DELETE_ADVERTISE_RESPONSE';
export const SEARCH_ADVERTISE_RESPONSE = 'SEARCH_ADVERTISE_RESPONSE';

export const CLEAN_ADVERTISE_LIST = 'CLEAN_ADVERTISE_LIST';
export const CLEAN_ADVERTISE_FORM = 'CLEAN_ADVERTISE_FORM';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';
