spring.profiles.active: dev

server: 
  port: 8082

---

spring:
  profiles: dev
  data:
    elasticsearch:
      cluster-name:  
      cluster-nodes: localhost:9300
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  
logging:
  level:
    root: INFO
    it.joint.microservices: DEBUG

--- 

test_rabbitmq_host: ${TEST_RABBITMQ_HOST:localhost}

spring:
  profiles: test
  data:
    elasticsearch:
      cluster-name:
      cluster-nodes:
  rabbitmq:
    host: ${test_rabbitmq_host}
    port: 5672
    username: guest
    password: guest
  
---

spring:
  profiles: testing
  data:
    elasticsearch: 
      cluster-name:
      cluster-nodes: advertise-search-elasticsearch:9300
  rabbitmq:
    host: advertise-rabbitmq
    port: 5672
    username: guest
    password: ${RABBITMQ_PASSWORD}
    
logging.config: logs/logback-spring.xml

---

spring:
  profiles: prod
  data:
    elasticsearch: 
      cluster-name:
      cluster-nodes: advertise-search-elasticsearch:9300
  rabbitmq:
    host: advertise-rabbitmq
    port: 5672
    username: guest
    password: ${RABBITMQ_PASSWORD}
    
logging.config: logs/logback-spring.xml
 